PieShop/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using PieShop.BusinessService;
using PieShop.Models;
using PieShop.ViewModels;
using System.Collections.Generic;

namespace PieShop.Controllers
{
    /// <summary>
    /// Contains all the methods for the Pie page
    /// </summary>
    public class PieController : Controller
    {
        private readonly IPieBusinessService _pieBusinessService;

        public PieController(IPieBusinessService pieBusinessService)
        {
            _pieBusinessService = pieBusinessService;
        }

        /// <summary>
        /// Returns the pies view list
        /// </summary>
        public ViewResult List(string category, decimal lowPrice = 0, decimal highPrice = 0, string sorting = "")
        {
            string currentCategory = string.Empty;
            _pieBusinessService.FilterByCategory(category, lowPrice, highPrice, out IEnumerable<Pie> pies, out currentCategory);
            pies = _pieBusinessService.SortPies(sorting, pies);

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }

        /// <summary>
        /// Search the pies based on the configurations
        /// </summary>
        [HttpGet]
        public ViewResult Search(string pieName, decimal lowPrice = 0, decimal highPrice = 0, string sorting = "")
        {
            IEnumerable<Pie> pies;
            string currentCategory = string.Empty;
            ViewBag.PieName = pieName;
            pies = _pieBusinessService.Search(pieName);
            pies = _pieBusinessService.PriceFilter(lowPrice, highPrice, pies);
            pies = _pieBusinessService.SortPies(sorting, pies);

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }



        /// <summary>
        /// Autocomplete for the search bar
        /// </summary>
        [HttpGet]
        public ActionResult AutocompleteSearch()
        {
            try
            {
                string term = HttpContext.Request.Query["term"].ToString();
                var names = _pieBusinessService.AutoComplete(term);

                return Ok(names);
            }
            catch
            {
                return BadRequest();
            }
        }

        /// <summary>
        /// Get all the Pies names
        /// </summary>
        [HttpGet]
        public IEnumerable<string> PiesNames()
        {
            return _pieBusinessService.GetPiesNames();
        }

        /// <summary>
        /// Get the Pie details
        /// </summary>
        public IActionResult Details(int id)
        {
            var pie = _pieBusinessService.GetPieById(id);
            if (pie == null)
            {
                return NotFound();
            }

            return View(pie);
        }
    }
}

PieShop/Views/Shared/Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

PieShop/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity


@inject SignInManager<PieShop.Auth.ApplicationUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
    </ul>
}

PieShop/Views/Shared/PieOfTheWeekSummary.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="Alternate Text" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="pie"
                   asp-action="Details"
                   asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

PieShop/Views/Shared/PieOverviewSummary.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="Alternate Text" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="pie" 
                   asp-action="Details"
                   asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

PieShop/Views/Shared/SearchPartial.cshtml
@model HomeViewModel

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(function () {
        var availableTags = [
            "ActionScript",
            "AppleScript",
            "Asp",
            "BASIC",
            "C",
            "C++",
            "Clojure",
            "COBOL",
            "ColdFusion",
            "Erlang",
            "Fortran",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Lisp",
            "Perl",
            "PHP",
            "Python",
            "Ruby",
            "Scala",
            "Scheme"
        ];
        $("#search").autocomplete({
            source: "/Pie/AutocompleteSearch"
        });
    });
</script>

<style>
    .ui-menu-item {
        padding-top: 10px;
    }
</style>

<ul class="nav navbar-nav navbar-right" style="margin-top:10px">
    <form class="form-inline mt-2 mt-md-0">
        <input id="search" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="pieName" style="background-color: white; color:cornflowerblue">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-controller="Pie" asp-action="Search">Search</button>
    </form>
</ul>

PieShop/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore
@using PieShop.Auth

@inject SignInManager<ApplicationUser> SignInManager
@inject IAuthorizationService AuthorizationService
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>

<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/lib/light-modal/dist/css/light-modal.min.css" rel="stylesheet" />
<link href="~/lib/light-modal/dist/css/animate.css" rel="stylesheet" />
<link href="~/Content/site.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                @await Component.InvokeAsync("CategoryMenu")
                <li><a asp-controller="Contact" asp-action="Index">Contact Us</a></li>

                @await Component.InvokeAsync("ShoppingCartSummary")
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrators"))
                {
                    @await Component.InvokeAsync("AdminMenu")
                }
            </ul>
            @await Html.PartialAsync("SearchPartial", new HomeViewModel())
            @await Html.PartialAsync("LoginPartial")
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                <img class="img-responsive" alt="My Pie Shop'" src="~/Images/bethanylogo.png" />
            </p>
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
    <audio src="~/Music/music-backgound.mp3" controls autoplay />
</div>



<script src="~/js/scripts.js"></script>
@RenderSection("scripts", required: false);